---
abstract: 'ftpd runner for tests'
author:
  - 'Taku Amano <taku@toi-planning.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-FTP-Server
no_index:
  directory:
    - inc
    - t
requires:
  Net::FTPServer: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/usualoma/p5-test-ftp-server.git
version: 0.012
